### ISSUE TITLE
Hidden label is inaccessible to screen-readers

### ISSUE THREAD

**Issue by GaryJones** [copyblogger/Genesis-Author-Pro#1]
https://github.com/copyblogger/Genesis-Author-Pro/blob/master/resources/css/admin.css#L5

The use of `display: none` on the label will make the label content inaccessible to screen-readers. Please apply the `screen-reader-text` class to the markup if your intent was just to visually hide it.

**Comment by NicktheGeek** [comment]
@gary, those are being hidden because they aren't relevant but aren't easily removed. It's a bit of a cheat but it works with minimal code.

**Comment by GaryJones** [comment]
If you're hiding the whole Layout metabox, then a `remove_meta_box()` call at something like `admin_init`, 11, should do that.
