### ISSUE TITLE
Entry pagination does not appear on single book pages

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/Genesis-Author-Pro#11]
#### Current behaviour

Entry content for single books paginated with `<--pagenext-->` does not result in page nav:
##### Page content

```
Page 1

<!--nextpage-->

Page 2

<!--nextpage-->

Page 3

<!--nextpage-->

Page 4
```
##### Result on a regular page

<img width="400" alt="test_content" src="https://cloud.githubusercontent.com/assets/647669/14499408/13a01288-0196-11e6-8622-060b792e7d27.png">
##### Result for a book

<img width="375" alt="test_something" src="https://cloud.githubusercontent.com/assets/647669/14499423/23c2519e-0196-11e6-93de-2fb15dc0a149.png">
#### Expected behaviour

Splitting book content with `<--pagenext-->` produces paginated links in the footer of single book pages.

We have a customer using the Books section to write short stories – they're using `<--pagenext-->` to split the content and expected to see a link to subsequent pages. I've offered a quick workaround for now:

``` php
<?php
//* Add <--pagenext--> pagination that Genesis Author Pro removes from single books
add_action( 'genesis_loop', 'spsupport_add_book_pagination' );

function spsupport_add_book_pagination() {
    if ( is_singular( 'books' ) ) {
        genesis_do_post_content_nav();
    }
}
```
#### To reproduce
1. Create a book from Library → Add New Book with this content:
   
   ```
   Page 1
   
   <!--nextpage-->
   
   Page 2
   ```
2. Visit the book page. 

The content will break after “Page 1”, but there's no way to progress to the next page.
#### Further info

The plugin's single book page template appears to [strip all actions](https://github.com/copyblogger/Genesis-Author-Pro/blob/059cc7a0a20d817d2097db3e666696dbc05280b1/functions/template.php#L60) hooked to `genesis_entry_content`, including this:

`add_action( 'genesis_entry_content', 'genesis_do_post_content_nav', 12 );`

Suggest either preventing that from being unhooked, or adding `genesis_do_post_content_nav()` to the single book template in `genesis_author_pro_single_content()`.

**Comment by NicktheGeek** [comment]
@nickcernis how does your fix work after we change this? I've actually never duplicated that function so will it output twice?

**Comment by nickcernis** [comment]
@NicktheGeek Yes, it would output twice on the book page. Happy to contact the site owner if needed to help with that, though. We've only had one report of this so far, so the workaround isn't widely used yet.

**Comment by NicktheGeek** [comment]
@nickcernis I just did a commit to develop_11. Can you give that a test to see if it works as expected? If it does I'll be able to update the WP plugin.

**Comment by nickcernis** [comment]
@NicktheGeek Looks good to me – thanks!

![test_book_pagination](https://cloud.githubusercontent.com/assets/647669/14579509/cd60158c-03a4-11e6-9a4d-6d73cd3c7d40.jpg)

**Comment by dreamwhisper** [comment]
@NicktheGeek I think this needs to be merged to RM. My test page isn't showing pagination.
http://jennifer-prod.cbmdev02.rmkr.net/book/test/
