### ISSUE TITLE
Update Featured text description 

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/Genesis-Author-Pro#12]
The Featured Text should include information that the text should be short and kept to one line for proper display out of the box.

![edit book jennifer-prod cbmdev02 rmkr net rainmaker platform 2016-05-13 08-30-28](https://cloud.githubusercontent.com/assets/1271053/15247913/3117ccfa-18e5-11e6-96c8-457a883f824d.png)

If long text is used, the default display can look like this:
![a new travel book - cbmdev02 2016-05-13 08-35-12](https://cloud.githubusercontent.com/assets/1271053/15247992/9dea341c-18e5-11e6-906e-cf8c566da9ce.png)

Current text:

> This will be added as featured text with the featured image.

Possible copy.

> Featured text will display as a banner with the featured image. For best display, the text should be one word or a short two-word phrase.

**Comment by dreamwhisper** [comment]
cc @jerodm40 @katyfb13 for copy.

**Comment by jerodm40** [comment]
This will be displayed as a banner with the featured image. For best display, the text should be one word or a short two-word phrase.

**Comment by omiq** [comment]
> a banner with

_along_ with?

**Comment by jerodm40** [comment]
Is it along with or on top of?

**Comment by dreamwhisper** [comment]
I would go with "along with" or "with".  We specifically never said at the top so designers could change the location/display with custom CSS in the theme. The location may not always be where we place it by default.

**Comment by dreamwhisper** [comment]
@jerodm40 what's our final text? :)

**Comment by jerodm40** [comment]
along with works for me!

**Comment by dreamwhisper** [comment]
This will be displayed as a banner along with the featured image. For best display, the text should be one word or a short two-word phrase.

@claregarrett we need proofing :) TY!

This change can be made to all branches.

**Comment by claregarrett** [comment]
Looks great :)

## 
- Sent from a mobile device  - please forgive brevity and/or spelling!

**Comment by NicktheGeek** [comment]
**Test Scenario**: 
- copy change

**Test Verification**: 
- [x] Verify the copy change

**Other Features/Areas Affected**:  NA

**Comment by dcronian** [comment]
Confirmed and merge ready.

**Comment by NicktheGeek** [comment]
don't see a way to mark it merged but it's merged
