### ISSUE TITLE
Update widget to optionally include book data

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/Genesis-Author-Pro#3]
Sample markup from @laurenmancke on the demo

``` html
<div class="featured-content">
<div class="entry">
<div class="author-pro-featured-image image-aligncenter">
<a title="Sample Book" href="http://demo.studiopress.com/author/book/sample-book/" class="aligncenter"><img width="360" height="570" itemprop="image" alt="cover-shooting-stars" class="entry-image attachment-books" src="http://demo.studiopress.com/author/files/2015/01/cover-shooting-stars-360x570.jpg"></a>
<h2 class="entry-title"><a href="http://demo.studiopress.com/author/book/sample-book/">Sample Book Title</a></h2>
<p style="margin-bottom: 28px" class="entry-meta">By <span itemprop="name" class="entry-author-name">Samuel Benjamin</span></p>
<p><a class="button" href="#">Purchase</a></p>
</div>
</div>
</div>
```

**Comment by laurenmancke** [comment]
I was just doing what it should look like on the front end. I can write the markup if we need that.

**Comment by dreamwhisper** [comment]
Options for the widget should include:
Widget title
book image
featured banner (custom)
book title (post title)
Author (custom)
price (custom)
blurb (excerpt/content limit see https://github.com/copyblogger/Genesis-Author-Pro/issues/4 )
button - we discussed making this button link to the page regardless of custom limit or excerpt, eliminate ellipses.

**Comment by dreamwhisper** [comment]
@NicktheGeek Can we move the Read More and the price inside the `entry-content` div?
