### ISSUE TITLE
Remove layout settings on all archive edit screens

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/Genesis-Author-Pro#38]
We hid layouts on /wp-admin/edit.php?post_type=books&page=genesis-cpt-archive-books

However, they currently show as available, along with simple sidebars settings on other archive pages. 

Since those pages are forced to full width, those options don't work:

![book author](https://cloud.githubusercontent.com/assets/1271053/17479862/080a351c-5d43-11e6-9d6b-0a495f235bb4.png)

Need to remove on each of these:
- Authors
- Series
- Tags

**Comment by dreamwhisper** [comment]
@marksabbath Looks like it was just done with CSS before: https://github.com/studiopress/Genesis-Author-Pro/blob/e11d038a8bbc0d2652a913999bc3b15cbb3cbba2/resources/css/admin.css

**Comment by marksabbath** [comment]
Hey, @dreamwhisper 

While investigating, I can see that those changes are there, but not working. I'll keep digging into that :)

**Comment by nickcernis** [comment]
Confirmed fixed in https://github.com/studiopress/Genesis-Author-Pro/pull/44. Leaving open until that is merged.
