### ISSUE TITLE
Change the author and URI from copyblogger to StudioPress

### ISSUE THREAD

**Issue by jaygidwitz** [copyblogger/Genesis-Author-Pro#40]
We need to change the author and URI from copyblogger to StudioPress.

<img width="809" alt="screenshot 2017-03-09 10 32 42" src="https://cloud.githubusercontent.com/assets/3248407/23764830/bf7499aa-04b3-11e7-89f8-7781a4b73b96.png">

**Comment by nickcernis** [comment]
Confirmed fixed by https://github.com/studiopress/Genesis-Author-Pro/pull/44. Leaving open until that is merged.
