### ISSUE TITLE
Gutenberg Block Capable?

### ISSUE THREAD

**Issue by robmcclel** [copyblogger/Genesis-Author-Pro#43]
I realize making this plugin block capable probably requires an entire re-write - but, is there a plan to modernize this plugin to work with Gutenberg?

It is, hands down, the best book management plugin out there.

**Comment by nickcernis** [comment]
Thank you for the kind words about the plugin, @robmcclel.

I don't have a firm timeline on Gutenberg support for Genesis Author Pro yet, but the StudioPress team will be reviewing this and other plugins in 2019 to see which would most benefit from blocks and other Gutenberg feature support.
