### ISSUE TITLE
Add filters for taxonomy slugs

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/Genesis-Author-Pro#7]
We need to add filters to allow all slugs to be filtered.
- book-author
- series
- book-tag

**Comment by DaisyOlsen** [comment]
Just a note here that as it stands the series permalink in this plugin actually conflicts with the podcast series permalink in Rainmaker.

**Comment by dreamwhisper** [comment]
> Just a note here that as it stands the series permalink in this plugin actually conflicts with the podcast series permalink in Rainmaker. 

Yep - it is noted on https://github.com/copyblogger/synthesis-platform/issues/2170

**Comment by dreamwhisper** [comment]
https://github.com/copyblogger/Genesis-Author-Pro/commit/1efb023b9b03aedef9f2a96631e6d6d4758186ba
