### ISSUE TITLE
Translations not currently working

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/Genesis-Author-Pro#8]
The plugin does not appear to load the text domain, so translated `.mo` files in the languages folder do not work in my tests.
#### Steps to reproduce
1. Add the following (incomplete) Dutch language files to `wp-content/plugins/genesis-author-pro/languages`: http://d.pr/f/19DTl+
2. Create a book named _The Shepherd's Crown_ and an author named _Terry Pratchett_, being sure to assign the author to the book.
3. Switch your WP language to “Nederlands” under Settings → General.

Expected behaviour:
- [Admin] Menu shows “Biblio” instead of “Library”.
- [Admin] Book Details meta box shows “Prijs” instead of “Price”.
- [Front] Book single page at `/book/the-shepherds-crown/` shows “Door Terry Pratchett” instead of “By Terry Pratchett”.
#### Suggested fix

These three changes fix the issue, in my tests:
1. Use the plugin basename for the languages directory:
   
   ``` php
   define( 'GENESIS_AUTHOR_PRO_LANGUAGES_DIR', dirname( plugin_basename( __FILE__ ) ) . '/languages/' );
   ```
2. Call `load_textdomain` on `init` instead of `plugins_loaded`.
3. Load the text domain before registering custom post types (so that custom post type labels are translated).

For changes two and three, that means doing this:

``` php
add_action( 'init', array( 'Genesis_Author_Pro'    , 'load_textdomain' ) );
add_action( 'init', array( 'Genesis_Author_Pro_CPT', 'init'            ) );
```

Instead of this:

``` php
add_action( 'after_setup_theme', array( 'Genesis_Author_Pro_CPT', 'init'            ), 1 );
add_action( 'plugins_loaded'   , array( 'Genesis_Author_Pro'    , 'load_textdomain' )    );
```

(Even though the [load_plugin_textdomain docs](https://codex.wordpress.org/Function_Reference/load_plugin_textdomain) say that you can hook as early as `plugins_loaded`, that's never worked reliably for me for some reason; hooking to `init` seems more common in other plugin code I've read.)

Happy to submit a PR if these changes seem okay.

**Comment by dreamwhisper** [comment]
@nickcernis Can you try the develop branch? We made some changes there that worked for a couple of testers.

**Comment by nickcernis** [comment]
@dreamwhisper All the above tests pass with the develop branch version. Thanks for mentioning that.

Happy to leave this open until develop is merged as a reminder that this is already fixed, but feel free to close and mark as invalid if you prefer.

**Comment by dreamwhisper** [comment]
Marked this as confirmed from user testing and Nick Cernis's testing. Not sure if it needs to stay open until rolled into the WP plugin or not @NicktheGeek
